//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_conselhoProfissional complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_conselhoProfissional">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="siglaConselho" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_conselhoProfissional"/>
 *         &lt;element name="numeroConselho" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_descricao15"/>
 *         &lt;element name="ufConselho" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_UF"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_conselhoProfissional", propOrder = {
    "siglaConselho",
    "numeroConselho",
    "ufConselho"
})
public class CtConselhoProfissional {

    @XmlElement(required = true)
    protected StConselhoProfissional siglaConselho;
    @XmlElement(required = true)
    protected String numeroConselho;
    @XmlElement(required = true)
    protected StUF ufConselho;

    /**
     * Gets the value of the siglaConselho property.
     * 
     * @return
     *     possible object is
     *     {@link StConselhoProfissional }
     *     
     */
    public StConselhoProfissional getSiglaConselho() {
        return siglaConselho;
    }

    /**
     * Sets the value of the siglaConselho property.
     * 
     * @param value
     *     allowed object is
     *     {@link StConselhoProfissional }
     *     
     */
    public void setSiglaConselho(StConselhoProfissional value) {
        this.siglaConselho = value;
    }

    /**
     * Gets the value of the numeroConselho property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroConselho() {
        return numeroConselho;
    }

    /**
     * Sets the value of the numeroConselho property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroConselho(String value) {
        this.numeroConselho = value;
    }

    /**
     * Gets the value of the ufConselho property.
     * 
     * @return
     *     possible object is
     *     {@link StUF }
     *     
     */
    public StUF getUfConselho() {
        return ufConselho;
    }

    /**
     * Sets the value of the ufConselho property.
     * 
     * @param value
     *     allowed object is
     *     {@link StUF }
     *     
     */
    public void setUfConselho(StUF value) {
        this.ufConselho = value;
    }

}
