//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_dadosConta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_dadosConta">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroFatura" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_descricao12" minOccurs="0"/>
 *         &lt;element name="lote">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="dadosLote" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_dadosLote" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="valorProcessadoFatura" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario"/>
 *         &lt;element name="valorLiberadoFatura" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario"/>
 *         &lt;element name="valorGlosaFatura" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_dadosConta", propOrder = {
    "numeroFatura",
    "lote",
    "valorProcessadoFatura",
    "valorLiberadoFatura",
    "valorGlosaFatura"
})
public class CtDadosConta {

    protected String numeroFatura;
    @XmlElement(required = true)
    protected CtDadosConta.Lote lote;
    @XmlElement(required = true)
    protected BigDecimal valorProcessadoFatura;
    @XmlElement(required = true)
    protected BigDecimal valorLiberadoFatura;
    protected BigDecimal valorGlosaFatura;

    /**
     * Gets the value of the numeroFatura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroFatura() {
        return numeroFatura;
    }

    /**
     * Sets the value of the numeroFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroFatura(String value) {
        this.numeroFatura = value;
    }

    /**
     * Gets the value of the lote property.
     * 
     * @return
     *     possible object is
     *     {@link CtDadosConta.Lote }
     *     
     */
    public CtDadosConta.Lote getLote() {
        return lote;
    }

    /**
     * Sets the value of the lote property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDadosConta.Lote }
     *     
     */
    public void setLote(CtDadosConta.Lote value) {
        this.lote = value;
    }

    /**
     * Gets the value of the valorProcessadoFatura property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorProcessadoFatura() {
        return valorProcessadoFatura;
    }

    /**
     * Sets the value of the valorProcessadoFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorProcessadoFatura(BigDecimal value) {
        this.valorProcessadoFatura = value;
    }

    /**
     * Gets the value of the valorLiberadoFatura property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorLiberadoFatura() {
        return valorLiberadoFatura;
    }

    /**
     * Sets the value of the valorLiberadoFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorLiberadoFatura(BigDecimal value) {
        this.valorLiberadoFatura = value;
    }

    /**
     * Gets the value of the valorGlosaFatura property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorGlosaFatura() {
        return valorGlosaFatura;
    }

    /**
     * Sets the value of the valorGlosaFatura property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorGlosaFatura(BigDecimal value) {
        this.valorGlosaFatura = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="dadosLote" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_dadosLote" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dadosLote"
    })
    public static class Lote {

        @XmlElement(required = true)
        protected List<CtDadosLote> dadosLote;

        /**
         * Gets the value of the dadosLote property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the dadosLote property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getDadosLote().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CtDadosLote }
         * 
         * 
         */
        public List<CtDadosLote> getDadosLote() {
            if (dadosLote == null) {
                dadosLote = new ArrayList<CtDadosLote>();
            }
            return this.dadosLote;
        }

    }

}
