//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_detalheGuiaOdonto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_detalheGuiaOdonto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="numeroGuiaPrestador" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_numeroGuia"/>
 *         &lt;element name="numeroGuiaOperadora" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_numeroGuia" minOccurs="0"/>
 *         &lt;element name="codigoBeneficiario" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_codigoBeneficiario"/>
 *         &lt;element name="NomeBeneficiario" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_nome"/>
 *         &lt;element name="procedimentoRealizado">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="procedimentosOdonto" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_procedimentoOdontoRealizado" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="valorTotalGlosaGuia" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario"/>
 *         &lt;element name="valorTotalLiberadoGuia" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario"/>
 *         &lt;element name="valorTotalProcessadoGuia" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_detalheGuiaOdonto", propOrder = {
    "numeroGuiaPrestador",
    "numeroGuiaOperadora",
    "codigoBeneficiario",
    "nomeBeneficiario",
    "procedimentoRealizado",
    "valorTotalGlosaGuia",
    "valorTotalLiberadoGuia",
    "valorTotalProcessadoGuia"
})
public class CtDetalheGuiaOdonto {

    @XmlElement(required = true)
    protected String numeroGuiaPrestador;
    protected String numeroGuiaOperadora;
    @XmlElement(required = true)
    protected String codigoBeneficiario;
    @XmlElement(name = "NomeBeneficiario", required = true)
    protected String nomeBeneficiario;
    @XmlElement(required = true)
    protected CtDetalheGuiaOdonto.ProcedimentoRealizado procedimentoRealizado;
    @XmlElement(required = true)
    protected BigDecimal valorTotalGlosaGuia;
    @XmlElement(required = true)
    protected BigDecimal valorTotalLiberadoGuia;
    @XmlElement(required = true)
    protected BigDecimal valorTotalProcessadoGuia;

    /**
     * Gets the value of the numeroGuiaPrestador property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroGuiaPrestador() {
        return numeroGuiaPrestador;
    }

    /**
     * Sets the value of the numeroGuiaPrestador property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroGuiaPrestador(String value) {
        this.numeroGuiaPrestador = value;
    }

    /**
     * Gets the value of the numeroGuiaOperadora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroGuiaOperadora() {
        return numeroGuiaOperadora;
    }

    /**
     * Sets the value of the numeroGuiaOperadora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroGuiaOperadora(String value) {
        this.numeroGuiaOperadora = value;
    }

    /**
     * Gets the value of the codigoBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoBeneficiario() {
        return codigoBeneficiario;
    }

    /**
     * Sets the value of the codigoBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoBeneficiario(String value) {
        this.codigoBeneficiario = value;
    }

    /**
     * Gets the value of the nomeBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeBeneficiario() {
        return nomeBeneficiario;
    }

    /**
     * Sets the value of the nomeBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeBeneficiario(String value) {
        this.nomeBeneficiario = value;
    }

    /**
     * Gets the value of the procedimentoRealizado property.
     * 
     * @return
     *     possible object is
     *     {@link CtDetalheGuiaOdonto.ProcedimentoRealizado }
     *     
     */
    public CtDetalheGuiaOdonto.ProcedimentoRealizado getProcedimentoRealizado() {
        return procedimentoRealizado;
    }

    /**
     * Sets the value of the procedimentoRealizado property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDetalheGuiaOdonto.ProcedimentoRealizado }
     *     
     */
    public void setProcedimentoRealizado(CtDetalheGuiaOdonto.ProcedimentoRealizado value) {
        this.procedimentoRealizado = value;
    }

    /**
     * Gets the value of the valorTotalGlosaGuia property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalGlosaGuia() {
        return valorTotalGlosaGuia;
    }

    /**
     * Sets the value of the valorTotalGlosaGuia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalGlosaGuia(BigDecimal value) {
        this.valorTotalGlosaGuia = value;
    }

    /**
     * Gets the value of the valorTotalLiberadoGuia property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalLiberadoGuia() {
        return valorTotalLiberadoGuia;
    }

    /**
     * Sets the value of the valorTotalLiberadoGuia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalLiberadoGuia(BigDecimal value) {
        this.valorTotalLiberadoGuia = value;
    }

    /**
     * Gets the value of the valorTotalProcessadoGuia property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalProcessadoGuia() {
        return valorTotalProcessadoGuia;
    }

    /**
     * Sets the value of the valorTotalProcessadoGuia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalProcessadoGuia(BigDecimal value) {
        this.valorTotalProcessadoGuia = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="procedimentosOdonto" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_procedimentoOdontoRealizado" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "procedimentosOdonto"
    })
    public static class ProcedimentoRealizado {

        @XmlElement(required = true)
        protected List<CtProcedimentoOdontoRealizado> procedimentosOdonto;

        /**
         * Gets the value of the procedimentosOdonto property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the procedimentosOdonto property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getProcedimentosOdonto().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CtProcedimentoOdontoRealizado }
         * 
         * 
         */
        public List<CtProcedimentoOdontoRealizado> getProcedimentosOdonto() {
            if (procedimentosOdonto == null) {
                procedimentosOdonto = new ArrayList<CtProcedimentoOdontoRealizado>();
            }
            return this.procedimentosOdonto;
        }

    }

}
