//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_diagnosticoAtendimento complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_diagnosticoAtendimento">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CID" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_diagnostico" minOccurs="0"/>
 *         &lt;element name="tipoDoenca" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_tipoDoenca" minOccurs="0"/>
 *         &lt;element name="tempoReferidoEvolucaoDoenca" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_tempoEvolucaoDoenca" minOccurs="0"/>
 *         &lt;element name="indicadorAcidente" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_indicadorAcidente" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_diagnosticoAtendimento", propOrder = {
    "cid",
    "tipoDoenca",
    "tempoReferidoEvolucaoDoenca",
    "indicadorAcidente"
})
@XmlSeeAlso({
    br.gov.ans.padroes.tiss.schemas.CtGuiaConsultaReapresentacao.HipoteseDiagnostica.class,
    br.gov.ans.padroes.tiss.schemas.CtGuiaConsulta.HipoteseDiagnostica.class
})
public class CtDiagnosticoAtendimento {

    @XmlElement(name = "CID")
    protected CtDiagnostico cid;
    @XmlElementRef(name = "tipoDoenca", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<StTipoDoenca> tipoDoenca;
    @XmlElementRef(name = "tempoReferidoEvolucaoDoenca", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<CtTempoEvolucaoDoenca> tempoReferidoEvolucaoDoenca;
    protected String indicadorAcidente;

    /**
     * Gets the value of the cid property.
     * 
     * @return
     *     possible object is
     *     {@link CtDiagnostico }
     *     
     */
    public CtDiagnostico getCID() {
        return cid;
    }

    /**
     * Sets the value of the cid property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDiagnostico }
     *     
     */
    public void setCID(CtDiagnostico value) {
        this.cid = value;
    }

    /**
     * Gets the value of the tipoDoenca property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link StTipoDoenca }{@code >}
     *     
     */
    public JAXBElement<StTipoDoenca> getTipoDoenca() {
        return tipoDoenca;
    }

    /**
     * Sets the value of the tipoDoenca property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link StTipoDoenca }{@code >}
     *     
     */
    public void setTipoDoenca(JAXBElement<StTipoDoenca> value) {
        this.tipoDoenca = value;
    }

    /**
     * Gets the value of the tempoReferidoEvolucaoDoenca property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link CtTempoEvolucaoDoenca }{@code >}
     *     
     */
    public JAXBElement<CtTempoEvolucaoDoenca> getTempoReferidoEvolucaoDoenca() {
        return tempoReferidoEvolucaoDoenca;
    }

    /**
     * Sets the value of the tempoReferidoEvolucaoDoenca property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link CtTempoEvolucaoDoenca }{@code >}
     *     
     */
    public void setTempoReferidoEvolucaoDoenca(JAXBElement<CtTempoEvolucaoDoenca> value) {
        this.tempoReferidoEvolucaoDoenca = value;
    }

    /**
     * Gets the value of the indicadorAcidente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorAcidente() {
        return indicadorAcidente;
    }

    /**
     * Sets the value of the indicadorAcidente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorAcidente(String value) {
        this.indicadorAcidente = value;
    }

}
