//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_diariaProrrogacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_diariaProrrogacao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoAcomodacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_tipoAcomodacao"/>
 *         &lt;element name="quantidadeDiaria" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_quantidade"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_diariaProrrogacao", propOrder = {
    "tipoAcomodacao",
    "quantidadeDiaria"
})
@XmlSeeAlso({
    br.gov.ans.padroes.tiss.schemas.MensagemTISS.OperadoraParaPrestador.AutorizacaoServico.DiariaProrrogacaoAutorizada.class,
    br.gov.ans.padroes.tiss.schemas.CtDiariaProrrogacaoAutorizada.class,
    br.gov.ans.padroes.tiss.schemas.CtSituacaoAutorizacao.DadosAutorizacao.CtDiariaProrrogacaoAutorizada.class
})
public class CtDiariaProrrogacao {

    @XmlElement(required = true)
    protected String tipoAcomodacao;
    @XmlElement(required = true)
    protected BigDecimal quantidadeDiaria;

    /**
     * Gets the value of the tipoAcomodacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoAcomodacao() {
        return tipoAcomodacao;
    }

    /**
     * Sets the value of the tipoAcomodacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoAcomodacao(String value) {
        this.tipoAcomodacao = value;
    }

    /**
     * Gets the value of the quantidadeDiaria property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeDiaria() {
        return quantidadeDiaria;
    }

    /**
     * Sets the value of the quantidadeDiaria property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeDiaria(BigDecimal value) {
        this.quantidadeDiaria = value;
    }

}
