//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_diariaProrrogacaoAutorizada complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_diariaProrrogacaoAutorizada">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.ans.gov.br/padroes/tiss/schemas}ct_diariaProrrogacao">
 *       &lt;sequence>
 *         &lt;element name="quantidadeAutorizada" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_quantidade" minOccurs="0"/>
 *         &lt;element name="motivoGlosa" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_motivoGlosa" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_diariaProrrogacaoAutorizada", propOrder = {
    "quantidadeAutorizada",
    "motivoGlosa"
})
public class CtDiariaProrrogacaoAutorizada
    extends CtDiariaProrrogacao
{

    protected BigDecimal quantidadeAutorizada;
    protected CtMotivoGlosa motivoGlosa;

    /**
     * Gets the value of the quantidadeAutorizada property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeAutorizada() {
        return quantidadeAutorizada;
    }

    /**
     * Sets the value of the quantidadeAutorizada property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeAutorizada(BigDecimal value) {
        this.quantidadeAutorizada = value;
    }

    /**
     * Gets the value of the motivoGlosa property.
     * 
     * @return
     *     possible object is
     *     {@link CtMotivoGlosa }
     *     
     */
    public CtMotivoGlosa getMotivoGlosa() {
        return motivoGlosa;
    }

    /**
     * Sets the value of the motivoGlosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtMotivoGlosa }
     *     
     */
    public void setMotivoGlosa(CtMotivoGlosa value) {
        this.motivoGlosa = value;
    }

}
