//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_diagnosticoSaidaInternacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_diagnosticoSaidaInternacao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="diagnosticoPrincipal" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_diagnostico" minOccurs="0"/>
 *         &lt;element name="indicadorAcidente" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_indicadorAcidente" minOccurs="0"/>
 *         &lt;element name="diagnosticosSecundarios" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_diagnosticosSecundarios" minOccurs="0"/>
 *         &lt;element name="motivoSaidaInternacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_motivoSaida"/>
 *         &lt;element name="obito" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_obitoInternacao" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_diagnosticoSaidaInternacao", propOrder = {
    "diagnosticoPrincipal",
    "indicadorAcidente",
    "diagnosticosSecundarios",
    "motivoSaidaInternacao",
    "obito"
})
public class CtDiagnosticoSaidaInternacao {

    protected CtDiagnostico diagnosticoPrincipal;
    protected String indicadorAcidente;
    protected CtDiagnosticosSecundarios diagnosticosSecundarios;
    @XmlElement(required = true)
    protected String motivoSaidaInternacao;
    protected List<CtObitoInternacao> obito;

    /**
     * Gets the value of the diagnosticoPrincipal property.
     * 
     * @return
     *     possible object is
     *     {@link CtDiagnostico }
     *     
     */
    public CtDiagnostico getDiagnosticoPrincipal() {
        return diagnosticoPrincipal;
    }

    /**
     * Sets the value of the diagnosticoPrincipal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDiagnostico }
     *     
     */
    public void setDiagnosticoPrincipal(CtDiagnostico value) {
        this.diagnosticoPrincipal = value;
    }

    /**
     * Gets the value of the indicadorAcidente property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicadorAcidente() {
        return indicadorAcidente;
    }

    /**
     * Sets the value of the indicadorAcidente property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicadorAcidente(String value) {
        this.indicadorAcidente = value;
    }

    /**
     * Gets the value of the diagnosticosSecundarios property.
     * 
     * @return
     *     possible object is
     *     {@link CtDiagnosticosSecundarios }
     *     
     */
    public CtDiagnosticosSecundarios getDiagnosticosSecundarios() {
        return diagnosticosSecundarios;
    }

    /**
     * Sets the value of the diagnosticosSecundarios property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDiagnosticosSecundarios }
     *     
     */
    public void setDiagnosticosSecundarios(CtDiagnosticosSecundarios value) {
        this.diagnosticosSecundarios = value;
    }

    /**
     * Gets the value of the motivoSaidaInternacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMotivoSaidaInternacao() {
        return motivoSaidaInternacao;
    }

    /**
     * Sets the value of the motivoSaidaInternacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMotivoSaidaInternacao(String value) {
        this.motivoSaidaInternacao = value;
    }

    /**
     * Gets the value of the obito property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the obito property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObito().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtObitoInternacao }
     * 
     * 
     */
    public List<CtObitoInternacao> getObito() {
        if (obito == null) {
            obito = new ArrayList<CtObitoInternacao>();
        }
        return this.obito;
    }

}
