//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_endereco complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_endereco">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoLogradouro" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_tipoLogradouro"/>
 *         &lt;element name="logradouro" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_logradouro"/>
 *         &lt;element name="numero" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_numeroLogradouro"/>
 *         &lt;element name="complemento" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_descricao15" minOccurs="0"/>
 *         &lt;element name="codigoIBGEMunicipio" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_codigoMunicipioIBGE"/>
 *         &lt;element name="municipio" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_descricao40" minOccurs="0"/>
 *         &lt;element name="codigoUF" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_UF"/>
 *         &lt;element name="cep" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_CEP"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_endereco", propOrder = {
    "tipoLogradouro",
    "logradouro",
    "numero",
    "complemento",
    "codigoIBGEMunicipio",
    "municipio",
    "codigoUF",
    "cep"
})
public class CtEndereco {

    @XmlElement(required = true)
    protected String tipoLogradouro;
    @XmlElement(required = true)
    protected String logradouro;
    @XmlElement(required = true)
    protected String numero;
    @XmlElementRef(name = "complemento", namespace = "http://www.ans.gov.br/padroes/tiss/schemas", type = JAXBElement.class, required = false)
    protected JAXBElement<String> complemento;
    @XmlElement(required = true)
    protected String codigoIBGEMunicipio;
    protected String municipio;
    @XmlElement(required = true)
    protected StUF codigoUF;
    @XmlElement(required = true)
    protected String cep;

    /**
     * Gets the value of the tipoLogradouro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoLogradouro() {
        return tipoLogradouro;
    }

    /**
     * Sets the value of the tipoLogradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoLogradouro(String value) {
        this.tipoLogradouro = value;
    }

    /**
     * Gets the value of the logradouro property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLogradouro() {
        return logradouro;
    }

    /**
     * Sets the value of the logradouro property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLogradouro(String value) {
        this.logradouro = value;
    }

    /**
     * Gets the value of the numero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumero(String value) {
        this.numero = value;
    }

    /**
     * Gets the value of the complemento property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public JAXBElement<String> getComplemento() {
        return complemento;
    }

    /**
     * Sets the value of the complemento property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link String }{@code >}
     *     
     */
    public void setComplemento(JAXBElement<String> value) {
        this.complemento = value;
    }

    /**
     * Gets the value of the codigoIBGEMunicipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodigoIBGEMunicipio() {
        return codigoIBGEMunicipio;
    }

    /**
     * Sets the value of the codigoIBGEMunicipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodigoIBGEMunicipio(String value) {
        this.codigoIBGEMunicipio = value;
    }

    /**
     * Gets the value of the municipio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMunicipio() {
        return municipio;
    }

    /**
     * Sets the value of the municipio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMunicipio(String value) {
        this.municipio = value;
    }

    /**
     * Gets the value of the codigoUF property.
     * 
     * @return
     *     possible object is
     *     {@link StUF }
     *     
     */
    public StUF getCodigoUF() {
        return codigoUF;
    }

    /**
     * Sets the value of the codigoUF property.
     * 
     * @param value
     *     allowed object is
     *     {@link StUF }
     *     
     */
    public void setCodigoUF(StUF value) {
        this.codigoUF = value;
    }

    /**
     * Gets the value of the cep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCep() {
        return cep;
    }

    /**
     * Sets the value of the cep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCep(String value) {
        this.cep = value;
    }

}
