//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_executanteComplementar complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_executanteComplementar">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="codigoProfissionalCompl" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_identificacaoPrestador"/>
 *         &lt;element name="nomeProfissionalCompl" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_nome"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_executanteComplementar", propOrder = {
    "codigoProfissionalCompl",
    "nomeProfissionalCompl"
})
public class CtExecutanteComplementar {

    @XmlElement(required = true)
    protected CtIdentificacaoPrestador codigoProfissionalCompl;
    @XmlElement(required = true)
    protected String nomeProfissionalCompl;

    /**
     * Gets the value of the codigoProfissionalCompl property.
     * 
     * @return
     *     possible object is
     *     {@link CtIdentificacaoPrestador }
     *     
     */
    public CtIdentificacaoPrestador getCodigoProfissionalCompl() {
        return codigoProfissionalCompl;
    }

    /**
     * Sets the value of the codigoProfissionalCompl property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtIdentificacaoPrestador }
     *     
     */
    public void setCodigoProfissionalCompl(CtIdentificacaoPrestador value) {
        this.codigoProfissionalCompl = value;
    }

    /**
     * Gets the value of the nomeProfissionalCompl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomeProfissionalCompl() {
        return nomeProfissionalCompl;
    }

    /**
     * Sets the value of the nomeProfissionalCompl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomeProfissionalCompl(String value) {
        this.nomeProfissionalCompl = value;
    }

}
