//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import br.gov.ans.padroes.tiss.schemas.CtAutorizacaoGuia;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ct_guiaResumoInternacaoReapresentacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_guiaResumoInternacaoReapresentacao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identificacaoGuiaInternacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_cabecalhoGuia"/>
 *         &lt;element name="numeroGuiaSolicitacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_numeroGuia" minOccurs="0"/>
 *         &lt;element name="dadosBeneficiario" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_beneficiario"/>
 *         &lt;element name="identificacaoExecutante" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_contratado"/>
 *         &lt;element name="dadosAutorizacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_autorizacaoGuia" minOccurs="0"/>
 *         &lt;element name="caraterInternacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_eletivaEmergencia"/>
 *         &lt;element name="acomodacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_tipoAcomodacao"/>
 *         &lt;element name="dataHoraInternacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_dataHora"/>
 *         &lt;element name="dataHoraSaidaInternacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_dataHora" minOccurs="0"/>
 *         &lt;element name="tipoInternacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_tipoInternacao"/>
 *         &lt;element name="regimeInternacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_regimeInternacao"/>
 *         &lt;element name="internacaoObstetrica" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_internacaoObstetrica" minOccurs="0"/>
 *         &lt;element name="obitoNeonatal" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_obitoNeonatal" minOccurs="0"/>
 *         &lt;element name="diagnosticosSaidaInternacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_diagnosticoSaidaInternacao"/>
 *         &lt;element name="procedimentosRealizados" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_procedimentoRevisao" minOccurs="0"/>
 *         &lt;element name="OPMUtilizadas" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_OPMUtilizadasRevisao" minOccurs="0"/>
 *         &lt;element name="outrasDespesas" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_outrasDespesasRevisao" minOccurs="0"/>
 *         &lt;element name="tipoFaturamento" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_tipoFaturamento"/>
 *         &lt;element name="valorTotal" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_valorTotalServicos" minOccurs="0"/>
 *         &lt;element name="observacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_observacao" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_guiaResumoInternacaoReapresentacao", propOrder = {
    "identificacaoGuiaInternacao",
    "numeroGuiaSolicitacao",
    "dadosBeneficiario",
    "identificacaoExecutante",
    "dadosAutorizacao",
    "caraterInternacao",
    "acomodacao",
    "dataHoraInternacao",
    "dataHoraSaidaInternacao",
    "tipoInternacao",
    "regimeInternacao",
    "internacaoObstetrica",
    "obitoNeonatal",
    "diagnosticosSaidaInternacao",
    "procedimentosRealizados",
    "opmUtilizadas",
    "outrasDespesas",
    "tipoFaturamento",
    "valorTotal",
    "observacao"
})
public class CtGuiaResumoInternacaoReapresentacao {

    @XmlElement(required = true)
    protected CtCabecalhoGuia identificacaoGuiaInternacao;
    protected String numeroGuiaSolicitacao;
    @XmlElement(required = true)
    protected CtBeneficiario dadosBeneficiario;
    @XmlElement(required = true)
    protected CtContratado identificacaoExecutante;
    protected CtAutorizacaoGuia dadosAutorizacao;
    @XmlElement(required = true)
    protected StEletivaEmergencia caraterInternacao;
    @XmlElement(required = true)
    protected String acomodacao;
    @XmlElement(required = true)
    protected XMLGregorianCalendar dataHoraInternacao;
    protected XMLGregorianCalendar dataHoraSaidaInternacao;
    @XmlElement(required = true)
    protected String tipoInternacao;
    @XmlElement(required = true)
    protected String regimeInternacao;
    protected CtInternacaoObstetrica internacaoObstetrica;
    protected CtObitoNeonatal obitoNeonatal;
    @XmlElement(required = true)
    protected CtDiagnosticoSaidaInternacao diagnosticosSaidaInternacao;
    protected CtProcedimentoRevisao procedimentosRealizados;
    @XmlElement(name = "OPMUtilizadas")
    protected CtOPMUtilizadasRevisao opmUtilizadas;
    protected CtOutrasDespesasRevisao outrasDespesas;
    @XmlElement(required = true)
    protected StTipoFaturamento tipoFaturamento;
    protected CtValorTotalServicos valorTotal;
    protected String observacao;

    /**
     * Gets the value of the identificacaoGuiaInternacao property.
     * 
     * @return
     *     possible object is
     *     {@link CtCabecalhoGuia }
     *     
     */
    public CtCabecalhoGuia getIdentificacaoGuiaInternacao() {
        return identificacaoGuiaInternacao;
    }

    /**
     * Sets the value of the identificacaoGuiaInternacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtCabecalhoGuia }
     *     
     */
    public void setIdentificacaoGuiaInternacao(CtCabecalhoGuia value) {
        this.identificacaoGuiaInternacao = value;
    }

    /**
     * Gets the value of the numeroGuiaSolicitacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumeroGuiaSolicitacao() {
        return numeroGuiaSolicitacao;
    }

    /**
     * Sets the value of the numeroGuiaSolicitacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumeroGuiaSolicitacao(String value) {
        this.numeroGuiaSolicitacao = value;
    }

    /**
     * Gets the value of the dadosBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link CtBeneficiario }
     *     
     */
    public CtBeneficiario getDadosBeneficiario() {
        return dadosBeneficiario;
    }

    /**
     * Sets the value of the dadosBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtBeneficiario }
     *     
     */
    public void setDadosBeneficiario(CtBeneficiario value) {
        this.dadosBeneficiario = value;
    }

    /**
     * Gets the value of the identificacaoExecutante property.
     * 
     * @return
     *     possible object is
     *     {@link CtContratado }
     *     
     */
    public CtContratado getIdentificacaoExecutante() {
        return identificacaoExecutante;
    }

    /**
     * Sets the value of the identificacaoExecutante property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtContratado }
     *     
     */
    public void setIdentificacaoExecutante(CtContratado value) {
        this.identificacaoExecutante = value;
    }

    /**
     * Gets the value of the dadosAutorizacao property.
     * 
     * @return
     *     possible object is
     *     {@link CtAutorizacaoGuia }
     *     
     */
    public CtAutorizacaoGuia getDadosAutorizacao() {
        return dadosAutorizacao;
    }

    /**
     * Sets the value of the dadosAutorizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtAutorizacaoGuia }
     *     
     */
    public void setDadosAutorizacao(CtAutorizacaoGuia value) {
        this.dadosAutorizacao = value;
    }

    /**
     * Gets the value of the caraterInternacao property.
     * 
     * @return
     *     possible object is
     *     {@link StEletivaEmergencia }
     *     
     */
    public StEletivaEmergencia getCaraterInternacao() {
        return caraterInternacao;
    }

    /**
     * Sets the value of the caraterInternacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link StEletivaEmergencia }
     *     
     */
    public void setCaraterInternacao(StEletivaEmergencia value) {
        this.caraterInternacao = value;
    }

    /**
     * Gets the value of the acomodacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAcomodacao() {
        return acomodacao;
    }

    /**
     * Sets the value of the acomodacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAcomodacao(String value) {
        this.acomodacao = value;
    }

    /**
     * Gets the value of the dataHoraInternacao property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataHoraInternacao() {
        return dataHoraInternacao;
    }

    /**
     * Sets the value of the dataHoraInternacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataHoraInternacao(XMLGregorianCalendar value) {
        this.dataHoraInternacao = value;
    }

    /**
     * Gets the value of the dataHoraSaidaInternacao property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDataHoraSaidaInternacao() {
        return dataHoraSaidaInternacao;
    }

    /**
     * Sets the value of the dataHoraSaidaInternacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDataHoraSaidaInternacao(XMLGregorianCalendar value) {
        this.dataHoraSaidaInternacao = value;
    }

    /**
     * Gets the value of the tipoInternacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoInternacao() {
        return tipoInternacao;
    }

    /**
     * Sets the value of the tipoInternacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoInternacao(String value) {
        this.tipoInternacao = value;
    }

    /**
     * Gets the value of the regimeInternacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRegimeInternacao() {
        return regimeInternacao;
    }

    /**
     * Sets the value of the regimeInternacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRegimeInternacao(String value) {
        this.regimeInternacao = value;
    }

    /**
     * Gets the value of the internacaoObstetrica property.
     * 
     * @return
     *     possible object is
     *     {@link CtInternacaoObstetrica }
     *     
     */
    public CtInternacaoObstetrica getInternacaoObstetrica() {
        return internacaoObstetrica;
    }

    /**
     * Sets the value of the internacaoObstetrica property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtInternacaoObstetrica }
     *     
     */
    public void setInternacaoObstetrica(CtInternacaoObstetrica value) {
        this.internacaoObstetrica = value;
    }

    /**
     * Gets the value of the obitoNeonatal property.
     * 
     * @return
     *     possible object is
     *     {@link CtObitoNeonatal }
     *     
     */
    public CtObitoNeonatal getObitoNeonatal() {
        return obitoNeonatal;
    }

    /**
     * Sets the value of the obitoNeonatal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtObitoNeonatal }
     *     
     */
    public void setObitoNeonatal(CtObitoNeonatal value) {
        this.obitoNeonatal = value;
    }

    /**
     * Gets the value of the diagnosticosSaidaInternacao property.
     * 
     * @return
     *     possible object is
     *     {@link CtDiagnosticoSaidaInternacao }
     *     
     */
    public CtDiagnosticoSaidaInternacao getDiagnosticosSaidaInternacao() {
        return diagnosticosSaidaInternacao;
    }

    /**
     * Sets the value of the diagnosticosSaidaInternacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDiagnosticoSaidaInternacao }
     *     
     */
    public void setDiagnosticosSaidaInternacao(CtDiagnosticoSaidaInternacao value) {
        this.diagnosticosSaidaInternacao = value;
    }

    /**
     * Gets the value of the procedimentosRealizados property.
     * 
     * @return
     *     possible object is
     *     {@link CtProcedimentoRevisao }
     *     
     */
    public CtProcedimentoRevisao getProcedimentosRealizados() {
        return procedimentosRealizados;
    }

    /**
     * Sets the value of the procedimentosRealizados property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtProcedimentoRevisao }
     *     
     */
    public void setProcedimentosRealizados(CtProcedimentoRevisao value) {
        this.procedimentosRealizados = value;
    }

    /**
     * Gets the value of the opmUtilizadas property.
     * 
     * @return
     *     possible object is
     *     {@link CtOPMUtilizadasRevisao }
     *     
     */
    public CtOPMUtilizadasRevisao getOPMUtilizadas() {
        return opmUtilizadas;
    }

    /**
     * Sets the value of the opmUtilizadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtOPMUtilizadasRevisao }
     *     
     */
    public void setOPMUtilizadas(CtOPMUtilizadasRevisao value) {
        this.opmUtilizadas = value;
    }

    /**
     * Gets the value of the outrasDespesas property.
     * 
     * @return
     *     possible object is
     *     {@link CtOutrasDespesasRevisao }
     *     
     */
    public CtOutrasDespesasRevisao getOutrasDespesas() {
        return outrasDespesas;
    }

    /**
     * Sets the value of the outrasDespesas property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtOutrasDespesasRevisao }
     *     
     */
    public void setOutrasDespesas(CtOutrasDespesasRevisao value) {
        this.outrasDespesas = value;
    }

    /**
     * Gets the value of the tipoFaturamento property.
     * 
     * @return
     *     possible object is
     *     {@link StTipoFaturamento }
     *     
     */
    public StTipoFaturamento getTipoFaturamento() {
        return tipoFaturamento;
    }

    /**
     * Sets the value of the tipoFaturamento property.
     * 
     * @param value
     *     allowed object is
     *     {@link StTipoFaturamento }
     *     
     */
    public void setTipoFaturamento(StTipoFaturamento value) {
        this.tipoFaturamento = value;
    }

    /**
     * Gets the value of the valorTotal property.
     * 
     * @return
     *     possible object is
     *     {@link CtValorTotalServicos }
     *     
     */
    public CtValorTotalServicos getValorTotal() {
        return valorTotal;
    }

    /**
     * Sets the value of the valorTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtValorTotalServicos }
     *     
     */
    public void setValorTotal(CtValorTotalServicos value) {
        this.valorTotal = value;
    }

    /**
     * Gets the value of the observacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservacao() {
        return observacao;
    }

    /**
     * Sets the value of the observacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservacao(String value) {
        this.observacao = value;
    }

}
