//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_guiaSolicitacaoProrrogacao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_guiaSolicitacaoProrrogacao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="identificacaoProrrogacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_cabecalhoGuia"/>
 *         &lt;element name="identificacaoGuiaReferencia" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_cabecalhoGuia"/>
 *         &lt;element name="dadosBeneficiario" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_beneficiario"/>
 *         &lt;element name="dadosSolicitante" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_solicitante"/>
 *         &lt;element name="indicacaoClinica" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_indicacaoClinica"/>
 *         &lt;element name="responsavelAutorizacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_nome" minOccurs="0"/>
 *         &lt;element name="procedimentosExamesSolicitados" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_procedimentosSolicitados" minOccurs="0"/>
 *         &lt;element name="diarias" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_diariaProrrogacao" minOccurs="0"/>
 *         &lt;element name="OPMsSolicitadas" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_OPMSolicitadas" minOccurs="0"/>
 *         &lt;element name="observacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_observacao" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_guiaSolicitacaoProrrogacao", propOrder = {
    "identificacaoProrrogacao",
    "identificacaoGuiaReferencia",
    "dadosBeneficiario",
    "dadosSolicitante",
    "indicacaoClinica",
    "responsavelAutorizacao",
    "procedimentosExamesSolicitados",
    "diarias",
    "opMsSolicitadas",
    "observacao"
})
public class CtGuiaSolicitacaoProrrogacao {

    @XmlElement(required = true)
    protected CtCabecalhoGuia identificacaoProrrogacao;
    @XmlElement(required = true)
    protected CtCabecalhoGuia identificacaoGuiaReferencia;
    @XmlElement(required = true)
    protected CtBeneficiario dadosBeneficiario;
    @XmlElement(required = true)
    protected CtSolicitante dadosSolicitante;
    @XmlElement(required = true)
    protected String indicacaoClinica;
    protected String responsavelAutorizacao;
    protected CtProcedimentosSolicitados procedimentosExamesSolicitados;
    protected CtDiariaProrrogacao diarias;
    @XmlElement(name = "OPMsSolicitadas")
    protected CtOPMSolicitadas opMsSolicitadas;
    protected String observacao;

    /**
     * Gets the value of the identificacaoProrrogacao property.
     * 
     * @return
     *     possible object is
     *     {@link CtCabecalhoGuia }
     *     
     */
    public CtCabecalhoGuia getIdentificacaoProrrogacao() {
        return identificacaoProrrogacao;
    }

    /**
     * Sets the value of the identificacaoProrrogacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtCabecalhoGuia }
     *     
     */
    public void setIdentificacaoProrrogacao(CtCabecalhoGuia value) {
        this.identificacaoProrrogacao = value;
    }

    /**
     * Gets the value of the identificacaoGuiaReferencia property.
     * 
     * @return
     *     possible object is
     *     {@link CtCabecalhoGuia }
     *     
     */
    public CtCabecalhoGuia getIdentificacaoGuiaReferencia() {
        return identificacaoGuiaReferencia;
    }

    /**
     * Sets the value of the identificacaoGuiaReferencia property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtCabecalhoGuia }
     *     
     */
    public void setIdentificacaoGuiaReferencia(CtCabecalhoGuia value) {
        this.identificacaoGuiaReferencia = value;
    }

    /**
     * Gets the value of the dadosBeneficiario property.
     * 
     * @return
     *     possible object is
     *     {@link CtBeneficiario }
     *     
     */
    public CtBeneficiario getDadosBeneficiario() {
        return dadosBeneficiario;
    }

    /**
     * Sets the value of the dadosBeneficiario property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtBeneficiario }
     *     
     */
    public void setDadosBeneficiario(CtBeneficiario value) {
        this.dadosBeneficiario = value;
    }

    /**
     * Gets the value of the dadosSolicitante property.
     * 
     * @return
     *     possible object is
     *     {@link CtSolicitante }
     *     
     */
    public CtSolicitante getDadosSolicitante() {
        return dadosSolicitante;
    }

    /**
     * Sets the value of the dadosSolicitante property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtSolicitante }
     *     
     */
    public void setDadosSolicitante(CtSolicitante value) {
        this.dadosSolicitante = value;
    }

    /**
     * Gets the value of the indicacaoClinica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndicacaoClinica() {
        return indicacaoClinica;
    }

    /**
     * Sets the value of the indicacaoClinica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndicacaoClinica(String value) {
        this.indicacaoClinica = value;
    }

    /**
     * Gets the value of the responsavelAutorizacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResponsavelAutorizacao() {
        return responsavelAutorizacao;
    }

    /**
     * Sets the value of the responsavelAutorizacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResponsavelAutorizacao(String value) {
        this.responsavelAutorizacao = value;
    }

    /**
     * Gets the value of the procedimentosExamesSolicitados property.
     * 
     * @return
     *     possible object is
     *     {@link CtProcedimentosSolicitados }
     *     
     */
    public CtProcedimentosSolicitados getProcedimentosExamesSolicitados() {
        return procedimentosExamesSolicitados;
    }

    /**
     * Sets the value of the procedimentosExamesSolicitados property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtProcedimentosSolicitados }
     *     
     */
    public void setProcedimentosExamesSolicitados(CtProcedimentosSolicitados value) {
        this.procedimentosExamesSolicitados = value;
    }

    /**
     * Gets the value of the diarias property.
     * 
     * @return
     *     possible object is
     *     {@link CtDiariaProrrogacao }
     *     
     */
    public CtDiariaProrrogacao getDiarias() {
        return diarias;
    }

    /**
     * Sets the value of the diarias property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtDiariaProrrogacao }
     *     
     */
    public void setDiarias(CtDiariaProrrogacao value) {
        this.diarias = value;
    }

    /**
     * Gets the value of the opMsSolicitadas property.
     * 
     * @return
     *     possible object is
     *     {@link CtOPMSolicitadas }
     *     
     */
    public CtOPMSolicitadas getOPMsSolicitadas() {
        return opMsSolicitadas;
    }

    /**
     * Sets the value of the opMsSolicitadas property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtOPMSolicitadas }
     *     
     */
    public void setOPMsSolicitadas(CtOPMSolicitadas value) {
        this.opMsSolicitadas = value;
    }

    /**
     * Gets the value of the observacao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObservacao() {
        return observacao;
    }

    /**
     * Sets the value of the observacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObservacao(String value) {
        this.observacao = value;
    }

}
