//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_identificacaoEquipe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_identificacaoEquipe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="membroEquipe" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="codigoProfissional" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_identificacaoPrestadorEquipe"/>
 *                   &lt;element name="identificacaoProfissional" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_profissionalExecutante"/>
 *                   &lt;element name="cpf" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_CPF" minOccurs="0"/>
 *                   &lt;element name="posicaoProfissional" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_posicaoProfissao"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_identificacaoEquipe", propOrder = {
    "membroEquipe"
})
public class CtIdentificacaoEquipe {

    @XmlElement(required = true)
    protected List<CtIdentificacaoEquipe.MembroEquipe> membroEquipe;

    /**
     * Gets the value of the membroEquipe property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the membroEquipe property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMembroEquipe().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtIdentificacaoEquipe.MembroEquipe }
     * 
     * 
     */
    public List<CtIdentificacaoEquipe.MembroEquipe> getMembroEquipe() {
        if (membroEquipe == null) {
            membroEquipe = new ArrayList<CtIdentificacaoEquipe.MembroEquipe>();
        }
        return this.membroEquipe;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="codigoProfissional" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_identificacaoPrestadorEquipe"/>
     *         &lt;element name="identificacaoProfissional" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_profissionalExecutante"/>
     *         &lt;element name="cpf" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_CPF" minOccurs="0"/>
     *         &lt;element name="posicaoProfissional" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_posicaoProfissao"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "codigoProfissional",
        "identificacaoProfissional",
        "cpf",
        "posicaoProfissional"
    })
    public static class MembroEquipe {

        @XmlElement(required = true)
        protected CtIdentificacaoPrestadorEquipe codigoProfissional;
        @XmlElement(required = true)
        protected CtProfissionalExecutante identificacaoProfissional;
        protected String cpf;
        @XmlElement(required = true)
        protected String posicaoProfissional;

        /**
         * Gets the value of the codigoProfissional property.
         * 
         * @return
         *     possible object is
         *     {@link CtIdentificacaoPrestadorEquipe }
         *     
         */
        public CtIdentificacaoPrestadorEquipe getCodigoProfissional() {
            return codigoProfissional;
        }

        /**
         * Sets the value of the codigoProfissional property.
         * 
         * @param value
         *     allowed object is
         *     {@link CtIdentificacaoPrestadorEquipe }
         *     
         */
        public void setCodigoProfissional(CtIdentificacaoPrestadorEquipe value) {
            this.codigoProfissional = value;
        }

        /**
         * Gets the value of the identificacaoProfissional property.
         * 
         * @return
         *     possible object is
         *     {@link CtProfissionalExecutante }
         *     
         */
        public CtProfissionalExecutante getIdentificacaoProfissional() {
            return identificacaoProfissional;
        }

        /**
         * Sets the value of the identificacaoProfissional property.
         * 
         * @param value
         *     allowed object is
         *     {@link CtProfissionalExecutante }
         *     
         */
        public void setIdentificacaoProfissional(CtProfissionalExecutante value) {
            this.identificacaoProfissional = value;
        }

        /**
         * Gets the value of the cpf property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCpf() {
            return cpf;
        }

        /**
         * Sets the value of the cpf property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCpf(String value) {
            this.cpf = value;
        }

        /**
         * Gets the value of the posicaoProfissional property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPosicaoProfissional() {
            return posicaoProfissional;
        }

        /**
         * Sets the value of the posicaoProfissional property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPosicaoProfissional(String value) {
            this.posicaoProfissional = value;
        }

    }

}
