//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_OPMSolicitadas complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_OPMSolicitadas">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OPMSolicitada" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="quantidadeSolicitada" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_quantidade"/>
 *                   &lt;element name="fabricante" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_descricao40" minOccurs="0"/>
 *                   &lt;element name="valor" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *                   &lt;element name="OPM" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_tabela"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_OPMSolicitadas", propOrder = {
    "opmSolicitada"
})
public class CtOPMSolicitadas {

    @XmlElement(name = "OPMSolicitada", required = true)
    protected List<CtOPMSolicitadas.OPMSolicitada> opmSolicitada;

    /**
     * Gets the value of the opmSolicitada property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the opmSolicitada property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOPMSolicitada().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CtOPMSolicitadas.OPMSolicitada }
     * 
     * 
     */
    public List<CtOPMSolicitadas.OPMSolicitada> getOPMSolicitada() {
        if (opmSolicitada == null) {
            opmSolicitada = new ArrayList<CtOPMSolicitadas.OPMSolicitada>();
        }
        return this.opmSolicitada;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="quantidadeSolicitada" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_quantidade"/>
     *         &lt;element name="fabricante" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_descricao40" minOccurs="0"/>
     *         &lt;element name="valor" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
     *         &lt;element name="OPM" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_tabela"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "quantidadeSolicitada",
        "fabricante",
        "valor",
        "opm"
    })
    public static class OPMSolicitada {

        @XmlElement(required = true)
        protected BigDecimal quantidadeSolicitada;
        protected String fabricante;
        protected BigDecimal valor;
        @XmlElement(name = "OPM", required = true)
        protected CtTabela opm;

        /**
         * Gets the value of the quantidadeSolicitada property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getQuantidadeSolicitada() {
            return quantidadeSolicitada;
        }

        /**
         * Sets the value of the quantidadeSolicitada property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setQuantidadeSolicitada(BigDecimal value) {
            this.quantidadeSolicitada = value;
        }

        /**
         * Gets the value of the fabricante property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getFabricante() {
            return fabricante;
        }

        /**
         * Sets the value of the fabricante property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setFabricante(String value) {
            this.fabricante = value;
        }

        /**
         * Gets the value of the valor property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getValor() {
            return valor;
        }

        /**
         * Sets the value of the valor property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setValor(BigDecimal value) {
            this.valor = value;
        }

        /**
         * Gets the value of the opm property.
         * 
         * @return
         *     possible object is
         *     {@link CtTabela }
         *     
         */
        public CtTabela getOPM() {
            return opm;
        }

        /**
         * Sets the value of the opm property.
         * 
         * @param value
         *     allowed object is
         *     {@link CtTabela }
         *     
         */
        public void setOPM(CtTabela value) {
            this.opm = value;
        }

    }

}
