//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ct_procedimentoOdontoRevisao complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_procedimentoOdontoRevisao">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="procedimentoOdontologia">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;extension base="{http://www.ans.gov.br/padroes/tiss/schemas}ct_procedimentoOdontologia">
 *                 &lt;sequence>
 *                   &lt;element name="dataRealizacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_data"/>
 *                 &lt;/sequence>
 *               &lt;/extension>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="valorTotal" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="quantidadeTotalUS" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="totalFranquiaCoparticipacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="justificativaRevisao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_justificativa"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_procedimentoOdontoRevisao", propOrder = {
    "procedimentoOdontologia",
    "valorTotal",
    "quantidadeTotalUS",
    "totalFranquiaCoparticipacao",
    "justificativaRevisao"
})
public class CtProcedimentoOdontoRevisao {

    @XmlElement(required = true)
    protected CtProcedimentoOdontoRevisao.ProcedimentoOdontologia procedimentoOdontologia;
    protected BigDecimal valorTotal;
    protected BigDecimal quantidadeTotalUS;
    protected BigDecimal totalFranquiaCoparticipacao;
    @XmlElement(required = true)
    protected String justificativaRevisao;

    /**
     * Gets the value of the procedimentoOdontologia property.
     * 
     * @return
     *     possible object is
     *     {@link CtProcedimentoOdontoRevisao.ProcedimentoOdontologia }
     *     
     */
    public CtProcedimentoOdontoRevisao.ProcedimentoOdontologia getProcedimentoOdontologia() {
        return procedimentoOdontologia;
    }

    /**
     * Sets the value of the procedimentoOdontologia property.
     * 
     * @param value
     *     allowed object is
     *     {@link CtProcedimentoOdontoRevisao.ProcedimentoOdontologia }
     *     
     */
    public void setProcedimentoOdontologia(CtProcedimentoOdontoRevisao.ProcedimentoOdontologia value) {
        this.procedimentoOdontologia = value;
    }

    /**
     * Gets the value of the valorTotal property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    /**
     * Sets the value of the valorTotal property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotal(BigDecimal value) {
        this.valorTotal = value;
    }

    /**
     * Gets the value of the quantidadeTotalUS property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getQuantidadeTotalUS() {
        return quantidadeTotalUS;
    }

    /**
     * Sets the value of the quantidadeTotalUS property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setQuantidadeTotalUS(BigDecimal value) {
        this.quantidadeTotalUS = value;
    }

    /**
     * Gets the value of the totalFranquiaCoparticipacao property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalFranquiaCoparticipacao() {
        return totalFranquiaCoparticipacao;
    }

    /**
     * Sets the value of the totalFranquiaCoparticipacao property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalFranquiaCoparticipacao(BigDecimal value) {
        this.totalFranquiaCoparticipacao = value;
    }

    /**
     * Gets the value of the justificativaRevisao property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJustificativaRevisao() {
        return justificativaRevisao;
    }

    /**
     * Sets the value of the justificativaRevisao property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJustificativaRevisao(String value) {
        this.justificativaRevisao = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;extension base="{http://www.ans.gov.br/padroes/tiss/schemas}ct_procedimentoOdontologia">
     *       &lt;sequence>
     *         &lt;element name="dataRealizacao" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_data"/>
     *       &lt;/sequence>
     *     &lt;/extension>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dataRealizacao"
    })
    public static class ProcedimentoOdontologia
        extends CtProcedimentoOdontologia
    {

        @XmlElement(required = true)
        protected XMLGregorianCalendar dataRealizacao;

        /**
         * Gets the value of the dataRealizacao property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataRealizacao() {
            return dataRealizacao;
        }

        /**
         * Sets the value of the dataRealizacao property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataRealizacao(XMLGregorianCalendar value) {
            this.dataRealizacao = value;
        }

    }

}
