//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_totalDemoOdonto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_totalDemoOdonto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="valorTotalGeralGlosa" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario"/>
 *         &lt;element name="valorTotalGeralLiberado" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario"/>
 *         &lt;element name="valorTotalProcessadoGuia" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_totalDemoOdonto", propOrder = {
    "valorTotalGeralGlosa",
    "valorTotalGeralLiberado",
    "valorTotalProcessadoGuia"
})
public class CtTotalDemoOdonto {

    @XmlElement(required = true)
    protected BigDecimal valorTotalGeralGlosa;
    @XmlElement(required = true)
    protected BigDecimal valorTotalGeralLiberado;
    @XmlElement(required = true)
    protected BigDecimal valorTotalProcessadoGuia;

    /**
     * Gets the value of the valorTotalGeralGlosa property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalGeralGlosa() {
        return valorTotalGeralGlosa;
    }

    /**
     * Sets the value of the valorTotalGeralGlosa property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalGeralGlosa(BigDecimal value) {
        this.valorTotalGeralGlosa = value;
    }

    /**
     * Gets the value of the valorTotalGeralLiberado property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalGeralLiberado() {
        return valorTotalGeralLiberado;
    }

    /**
     * Sets the value of the valorTotalGeralLiberado property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalGeralLiberado(BigDecimal value) {
        this.valorTotalGeralLiberado = value;
    }

    /**
     * Gets the value of the valorTotalProcessadoGuia property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getValorTotalProcessadoGuia() {
        return valorTotalProcessadoGuia;
    }

    /**
     * Sets the value of the valorTotalProcessadoGuia property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setValorTotalProcessadoGuia(BigDecimal value) {
        this.valorTotalProcessadoGuia = value;
    }

}
