//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ct_valorTotalServicos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ct_valorTotalServicos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="servicosExecutados" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="diarias" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="taxas" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="materiais" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="medicamentos" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="gases" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *         &lt;element name="totalGeral" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_valorMonetario" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ct_valorTotalServicos", propOrder = {
    "servicosExecutados",
    "diarias",
    "taxas",
    "materiais",
    "medicamentos",
    "gases",
    "totalGeral"
})
public class CtValorTotalServicos {

    protected BigDecimal servicosExecutados;
    protected BigDecimal diarias;
    protected BigDecimal taxas;
    protected BigDecimal materiais;
    protected BigDecimal medicamentos;
    protected BigDecimal gases;
    protected BigDecimal totalGeral;

    /**
     * Gets the value of the servicosExecutados property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getServicosExecutados() {
        return servicosExecutados;
    }

    /**
     * Sets the value of the servicosExecutados property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setServicosExecutados(BigDecimal value) {
        this.servicosExecutados = value;
    }

    /**
     * Gets the value of the diarias property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getDiarias() {
        return diarias;
    }

    /**
     * Sets the value of the diarias property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setDiarias(BigDecimal value) {
        this.diarias = value;
    }

    /**
     * Gets the value of the taxas property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTaxas() {
        return taxas;
    }

    /**
     * Sets the value of the taxas property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTaxas(BigDecimal value) {
        this.taxas = value;
    }

    /**
     * Gets the value of the materiais property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMateriais() {
        return materiais;
    }

    /**
     * Sets the value of the materiais property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMateriais(BigDecimal value) {
        this.materiais = value;
    }

    /**
     * Gets the value of the medicamentos property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMedicamentos() {
        return medicamentos;
    }

    /**
     * Sets the value of the medicamentos property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMedicamentos(BigDecimal value) {
        this.medicamentos = value;
    }

    /**
     * Gets the value of the gases property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getGases() {
        return gases;
    }

    /**
     * Sets the value of the gases property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setGases(BigDecimal value) {
        this.gases = value;
    }

    /**
     * Gets the value of the totalGeral property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalGeral() {
        return totalGeral;
    }

    /**
     * Sets the value of the totalGeral property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalGeral(BigDecimal value) {
        this.totalGeral = value;
    }

}
