//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//


package br.gov.ans.padroes.tiss.schemas;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for nodo_tissnet complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="nodo_tissnet">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="operadora" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_registroANS"/>
 *         &lt;element name="pontoAPonto" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;choice>
 *                   &lt;element name="socket" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_hostporta"/>
 *                   &lt;element name="service" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl"/>
 *                 &lt;/choice>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="webServices" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="tissCancelaGuia" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
 *                   &lt;element name="tissLoteGuias" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
 *                   &lt;element name="tissSolicitacaoAnaliseConta" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
 *                   &lt;element name="tissSolicitacaoDemonstrativoPagamento" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
 *                   &lt;element name="tissSolicitacaoProcedimento" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
 *                   &lt;element name="tissSolicitacaoStatusProtocolo" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
 *                   &lt;element name="tissVerificaElegibilidade" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "nodo_tissnet", propOrder = {
    "operadora",
    "pontoAPonto",
    "webServices"
})
public class NodoTissnet {

    @XmlElement(required = true)
    protected String operadora;
    protected NodoTissnet.PontoAPonto pontoAPonto;
    protected NodoTissnet.WebServices webServices;

    /**
     * Gets the value of the operadora property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperadora() {
        return operadora;
    }

    /**
     * Sets the value of the operadora property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperadora(String value) {
        this.operadora = value;
    }

    /**
     * Gets the value of the pontoAPonto property.
     * 
     * @return
     *     possible object is
     *     {@link NodoTissnet.PontoAPonto }
     *     
     */
    public NodoTissnet.PontoAPonto getPontoAPonto() {
        return pontoAPonto;
    }

    /**
     * Sets the value of the pontoAPonto property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodoTissnet.PontoAPonto }
     *     
     */
    public void setPontoAPonto(NodoTissnet.PontoAPonto value) {
        this.pontoAPonto = value;
    }

    /**
     * Gets the value of the webServices property.
     * 
     * @return
     *     possible object is
     *     {@link NodoTissnet.WebServices }
     *     
     */
    public NodoTissnet.WebServices getWebServices() {
        return webServices;
    }

    /**
     * Sets the value of the webServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link NodoTissnet.WebServices }
     *     
     */
    public void setWebServices(NodoTissnet.WebServices value) {
        this.webServices = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;choice>
     *         &lt;element name="socket" type="{http://www.ans.gov.br/padroes/tiss/schemas}ct_hostporta"/>
     *         &lt;element name="service" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl"/>
     *       &lt;/choice>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "socket",
        "service"
    })
    public static class PontoAPonto {

        protected CtHostporta socket;
        protected String service;

        /**
         * Gets the value of the socket property.
         * 
         * @return
         *     possible object is
         *     {@link CtHostporta }
         *     
         */
        public CtHostporta getSocket() {
            return socket;
        }

        /**
         * Sets the value of the socket property.
         * 
         * @param value
         *     allowed object is
         *     {@link CtHostporta }
         *     
         */
        public void setSocket(CtHostporta value) {
            this.socket = value;
        }

        /**
         * Gets the value of the service property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getService() {
            return service;
        }

        /**
         * Sets the value of the service property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setService(String value) {
            this.service = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="tissCancelaGuia" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
     *         &lt;element name="tissLoteGuias" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
     *         &lt;element name="tissSolicitacaoAnaliseConta" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
     *         &lt;element name="tissSolicitacaoDemonstrativoPagamento" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
     *         &lt;element name="tissSolicitacaoProcedimento" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
     *         &lt;element name="tissSolicitacaoStatusProtocolo" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
     *         &lt;element name="tissVerificaElegibilidade" type="{http://www.ans.gov.br/padroes/tiss/schemas}st_wsurl" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tissCancelaGuia",
        "tissLoteGuias",
        "tissSolicitacaoAnaliseConta",
        "tissSolicitacaoDemonstrativoPagamento",
        "tissSolicitacaoProcedimento",
        "tissSolicitacaoStatusProtocolo",
        "tissVerificaElegibilidade"
    })
    public static class WebServices {

        protected String tissCancelaGuia;
        protected String tissLoteGuias;
        protected String tissSolicitacaoAnaliseConta;
        protected String tissSolicitacaoDemonstrativoPagamento;
        protected String tissSolicitacaoProcedimento;
        protected String tissSolicitacaoStatusProtocolo;
        protected String tissVerificaElegibilidade;

        /**
         * Gets the value of the tissCancelaGuia property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTissCancelaGuia() {
            return tissCancelaGuia;
        }

        /**
         * Sets the value of the tissCancelaGuia property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTissCancelaGuia(String value) {
            this.tissCancelaGuia = value;
        }

        /**
         * Gets the value of the tissLoteGuias property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTissLoteGuias() {
            return tissLoteGuias;
        }

        /**
         * Sets the value of the tissLoteGuias property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTissLoteGuias(String value) {
            this.tissLoteGuias = value;
        }

        /**
         * Gets the value of the tissSolicitacaoAnaliseConta property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTissSolicitacaoAnaliseConta() {
            return tissSolicitacaoAnaliseConta;
        }

        /**
         * Sets the value of the tissSolicitacaoAnaliseConta property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTissSolicitacaoAnaliseConta(String value) {
            this.tissSolicitacaoAnaliseConta = value;
        }

        /**
         * Gets the value of the tissSolicitacaoDemonstrativoPagamento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTissSolicitacaoDemonstrativoPagamento() {
            return tissSolicitacaoDemonstrativoPagamento;
        }

        /**
         * Sets the value of the tissSolicitacaoDemonstrativoPagamento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTissSolicitacaoDemonstrativoPagamento(String value) {
            this.tissSolicitacaoDemonstrativoPagamento = value;
        }

        /**
         * Gets the value of the tissSolicitacaoProcedimento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTissSolicitacaoProcedimento() {
            return tissSolicitacaoProcedimento;
        }

        /**
         * Sets the value of the tissSolicitacaoProcedimento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTissSolicitacaoProcedimento(String value) {
            this.tissSolicitacaoProcedimento = value;
        }

        /**
         * Gets the value of the tissSolicitacaoStatusProtocolo property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTissSolicitacaoStatusProtocolo() {
            return tissSolicitacaoStatusProtocolo;
        }

        /**
         * Sets the value of the tissSolicitacaoStatusProtocolo property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTissSolicitacaoStatusProtocolo(String value) {
            this.tissSolicitacaoStatusProtocolo = value;
        }

        /**
         * Gets the value of the tissVerificaElegibilidade property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTissVerificaElegibilidade() {
            return tissVerificaElegibilidade;
        }

        /**
         * Sets the value of the tissVerificaElegibilidade property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTissVerificaElegibilidade(String value) {
            this.tissVerificaElegibilidade = value;
        }

    }

}
