//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.03 at 01:07:43 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ans.gov.br/padroes/tiss/schemas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package br.gov.ans.padroes.tiss.schemas;

//        xmlns = {
//            @javax.xml.bind.annotation.XmlNs(namespaceURI = "http://www.ans.gov.br/padroes/tiss/schemas", prefix = "ansTISS"),  
//            @javax.xml.bind.annotation.XmlNs(namespaceURI = "br.gov.ans.padroes.tiss.schemas:ansTISS", prefix = "ansTISS")  
//        },